
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/paic/CoolPay
	@mkdir  ../../sea-modules/paic/CoolPay
	@mkdir  ../../sea-modules/paic/CoolPay/1.0.0
	@cp     dist/*.* ../../sea-modules/paic/CoolPay/1.0.0
	@echo
	@echo   " deploy to seajs-modules/paic/CoolPay/1.0.0"
	@echo
